/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teoriacolas;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class Montecarlo extends javax.swing.JFrame {

    Thread th;
    String name;
    ThreadGUI h;
    
    public Montecarlo() {
        setLayout(null);
        initComponents();
        this.getContentPane().setBackground(Color.gray);
        setLocationRelativeTo(null);
        setPreferredSize(new Dimension(11800, 10000));
        h = new ThreadGUI();
        h.recibeTxtTotal(txtTotal);
        h.recibeTxtRetiro(txtRetiro);
        h.recibeTxtConsulta(txtConsulta);
        h.recibeTxtTransferencia(txtTransferencia);
        h.recibeTxtOtros(txtOtros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRetiro = new javax.swing.JTextField();
        txtConsulta = new javax.swing.JTextField();
        txtTransferencia = new javax.swing.JTextField();
        txtOtros = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnRelativa = new javax.swing.JButton();
        txtRetiroRelativa = new javax.swing.JTextField();
        txtOtrosRelativa = new javax.swing.JTextField();
        txtTransferenciaRelativa = new javax.swing.JTextField();
        txtConsultaRelativa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtOtrosAbsoluta = new javax.swing.JTextField();
        txtConsultaAbsoluta = new javax.swing.JTextField();
        txtTransferenciaAbsoluta = new javax.swing.JTextField();
        txtRetiroAbsoluta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPersonas = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUsuarios = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAleatorio = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAleatorio2 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtOperacion = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTiempoOperacion = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtTiempoLlegada = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtHoraLlegada = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtHoraAtencion = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextPane();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("TEORIA DE COLAS");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Llegadas Totales");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RETIRO");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CONSULTA");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("TRANSFERENCIA");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("OTROS");

        txtRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetiroActionPerformed(evt);
            }
        });

        txtConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaActionPerformed(evt);
            }
        });

        btnOk.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Total de cada operación");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Frecuencia relativa");

        btnRelativa.setText("Calcular");
        btnRelativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelativaActionPerformed(evt);
            }
        });

        txtRetiroRelativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetiroRelativaActionPerformed(evt);
            }
        });

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtConsultaAbsoluta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaAbsolutaActionPerformed(evt);
            }
        });

        txtTransferenciaAbsoluta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransferenciaAbsolutaActionPerformed(evt);
            }
        });

        txtRetiroAbsoluta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetiroAbsolutaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Ingrese el numero de personas totales");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Frecuencia absoluta");

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Usuarios");

        jLabel12.setText("Hora llegada");

        jLabel13.setText("Aleatorio 1");

        jLabel14.setText("Salida");

        jLabel15.setText("Aleatorio 2");

        jLabel16.setText("Tiempo operación");

        jLabel17.setText("Op. seleccionada");

        jLabel18.setText("Hora atención");

        jLabel19.setText("Tiempo Llegada");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtUsuarios.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jScrollPane1.setViewportView(txtUsuarios);

        txtAleatorio.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jScrollPane2.setViewportView(txtAleatorio);

        txtAleatorio2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jScrollPane3.setViewportView(txtAleatorio2);

        txtOperacion.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jScrollPane5.setViewportView(txtOperacion);

        txtTiempoOperacion.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jScrollPane4.setViewportView(txtTiempoOperacion);

        txtTiempoLlegada.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jScrollPane6.setViewportView(txtTiempoLlegada);

        txtHoraLlegada.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jScrollPane7.setViewportView(txtHoraLlegada);

        txtHoraAtencion.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jScrollPane8.setViewportView(txtHoraAtencion);

        txtSalida.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jScrollPane9.setViewportView(txtSalida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(txtConsultaRelativa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(339, 339, 339)
                        .addComponent(txtConsultaAbsoluta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(txtTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(txtTransferenciaRelativa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(339, 339, 339)
                        .addComponent(txtTransferenciaAbsoluta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158)
                                .addComponent(txtRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addComponent(txtRetiroRelativa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(339, 339, 339)
                                .addComponent(txtRetiroAbsoluta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(42, 42, 42)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRelativa)
                                        .addGap(37, 37, 37)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(302, 302, 302)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(244, 244, 244)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(130, 130, 130)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(jLabel19)
                                .addGap(23, 23, 23)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(jScrollPane7))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addComponent(txtOtrosRelativa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(339, 339, 339)
                                .addComponent(txtOtrosAbsoluta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(637, 637, 637)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(6, 6, 6)
                                .addComponent(btnRelativa))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOk)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRetiroRelativa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRetiroAbsoluta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsultaRelativa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsultaAbsoluta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransferenciaRelativa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransferenciaAbsoluta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOtrosRelativa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOtrosAbsoluta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jLabel15)
                        .addComponent(jLabel14)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        h.start();
        
    }//GEN-LAST:event_btnOkActionPerformed

    private void txtConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaActionPerformed

    private void btnRelativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelativaActionPerformed
        try{
            double cant1, cant2, cant3, cant4;
            
            cant1 = Integer.parseInt(txtRetiro.getText());
            cant2 = Integer.parseInt(txtConsulta.getText());
            cant3 = Integer.parseInt(txtTransferencia.getText());
            cant4 = Integer.parseInt(txtOtros.getText());
        
            double relativa1 = cant1 / (cant1 + cant2 + cant3 + cant4);
            double relativa2 = cant2 / (cant1 + cant2 + cant3 + cant4);
            double relativa3 = cant3 / (cant1 + cant2 + cant3 + cant4);
            double relativa4 = cant4 / (cant1 + cant2 + cant3 + cant4);
        
            txtRetiroRelativa.setText(String.valueOf(relativa1));
            txtConsultaRelativa.setText(String.valueOf(relativa2));
            txtTransferenciaRelativa.setText(String.valueOf(relativa3));
            txtOtrosRelativa.setText(String.valueOf(relativa4));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_btnRelativaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            float getRelativaRetiro, getRelativaConsulta, getRelativaTransferencia, getRelativaOtros;
        
            getRelativaRetiro = Float.parseFloat(txtRetiroRelativa.getText());
            getRelativaConsulta = Float.parseFloat(txtConsultaRelativa.getText());
            getRelativaTransferencia = Float.parseFloat(txtTransferenciaRelativa.getText());
            getRelativaOtros = Float.parseFloat(txtOtrosRelativa.getText());
        
            float absolutaRetiro = getRelativaRetiro;
            float absolutaConsulta = getRelativaRetiro + getRelativaConsulta;
            float absolutaTransferencia = getRelativaTransferencia + absolutaConsulta;
            float absolutaOtros = getRelativaOtros + absolutaTransferencia;
        
            txtRetiroAbsoluta.setText(String.valueOf(absolutaRetiro));
            txtConsultaAbsoluta.setText(String.valueOf(absolutaConsulta));
            txtTransferenciaAbsoluta.setText(String.valueOf(absolutaTransferencia));
            txtOtrosAbsoluta.setText(String.valueOf(absolutaOtros));
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTransferenciaAbsolutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransferenciaAbsolutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransferenciaAbsolutaActionPerformed

    private void txtConsultaAbsolutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaAbsolutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaAbsolutaActionPerformed

    private void txtRetiroAbsolutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetiroAbsolutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetiroAbsolutaActionPerformed

    private void txtRetiroRelativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetiroRelativaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetiroRelativaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetiroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int personasTotales;

        float media = 1F; //Realmente deberia ser 2
        float desviacion = 0.1F; //Deberia ser 0.2
        //La razon por las que se divide entre dos es que la desviacion estandar admite datos de rango 0 y 1
        
        double hora = 0;
        double horaStatic = 60;
        double contHora = 4;

        hora = horaStatic * contHora;

        double horaFinal = hora / 60;

        int cont1 = 0, cont2 = 0, cont3 = 0, cont4 = 0;
        personasTotales = Integer.parseInt(txtPersonas.getText());
        
        float[] tiempoLlegada = new float[personasTotales];
        //Obtener lista total de personas
        for(int i = 1; i <= personasTotales; i++){
            txtUsuarios.setText(txtUsuarios.getText()+ " "+ i + "\n");
            System.out.println(i);
            
        }
        
        //Obtener numeros aleatorios 1
        for(int i = 1; i <= personasTotales; i++){
            double numero = Math.random();
            float numeroFloat;
            numeroFloat = (float) numero;
            txtAleatorio.setText(txtAleatorio.getText() + i + "-. " + numeroFloat + "\n");
            System.out.println(i + " " + numeroFloat);
        }
        
        //Obtener operaciones
        for(int i = 1; i <= personasTotales; i++){
            double numero = Math.random();
            System.out.print(i + " ");
            if(numero > 0.1 && numero < 0.25){
                cont1 += 1;
                txtOperacion.setText(txtOperacion.getText() + i + "-. Transferencia\n");
            }else if(numero > 0.25 && numero < 0.50){
                cont2 += 1;
                txtOperacion.setText(txtOperacion.getText() + i + "-. Retiro\n");
            }else if(numero > 0.51 && numero < 0.75){
                cont3 += 1;
                txtOperacion.setText(txtOperacion.getText() + i + "-. Consulta\n");
            }else{
                cont4 += 1;
                txtOperacion.setText(txtOperacion.getText() + i + "-. Otros\n");
            }
        }
        
        //Obtener tiempo de llegada
        try{
            float contTiempo = 0.02F;
            float contTiempo2 = 0.03F;
            float contTiempo3 = 0.04F;
            float llegada = 0;

            for(int i = 1; i <= personasTotales; i++){
                double y = Math.random();
                float x = (float) y;
                if(x > 0.1 && x < 0.25){
                    llegada = contTiempo3;
                }else if(x > 0.25 && x < 0.60){
                    llegada = contTiempo2;
                }else if(x > 0.60 && x < 0.99){
                    llegada = contTiempo;
                }

                if(llegada > 7.60 && llegada < 7.99){
                    llegada = 8;
                }else if(llegada > 8.60 && llegada < 8.99){
                    llegada = 9;
                }else if(llegada > 9.60 && llegada < 9.99){
                    llegada = 10;
                }else if(llegada > 10.60 && llegada < 10.99){
                    llegada = 11;
                }else if(llegada > 11.60 && llegada < 11.99){
                    llegada = 12;
                }else if(llegada > 12.60 && llegada < 12.99){
                    llegada = 13;
                }else if(llegada > 13.60 && llegada < 13.99){
                    llegada = 14;
                }else if(llegada > 14.60 && llegada < 14.99){
                    llegada = 15;
                }else if(llegada > 15.60 && llegada < 15.99){
                    llegada = 15;
                }else if(llegada > 16.60 && llegada < 16.99){
                    llegada = 17;
                }

                txtTiempoLlegada.setText(txtTiempoLlegada.getText() + i + "-. " + llegada + "\n");
            }
            
            /*for(int i = 0; i < personasTotales; i++){
                //tiempoLlegada[i] = (float) (Math.random());
                //txtTiempoLlegada.setText(txtTiempoLlegada.getText() + i + "-. " + tiempoLlegada[i] + "\n");
                horaFinal++;
                txtTiempoLlegada.setText(txtTiempoLlegada.getText() + i + "-. " + horaFinal + "\n");
            }*/
        }catch(Exception e){
            System.out.println("Error: " + e);
        }
        
        //Obtener hora llegada
        try{
            float contTiempo = 0.02F;
            float contTiempo2 = 0.03F;
            float contTiempo3 = 0.04F;
            float llegada = 7;

            for(int i = 1; i <= personasTotales; i++){
                double y = Math.random();
                float x = (float) y;
                if(x > 0.1 && x < 0.25){
                    llegada = llegada + contTiempo3;
                }else if(x > 0.25 && x < 0.60){
                    llegada = llegada + contTiempo2;
                }else if(x > 0.60 && x < 0.99){
                    llegada = llegada + contTiempo;
                }

                if(llegada > 7.60 && llegada < 7.99){
                    llegada = 8;
                }else if(llegada > 8.60 && llegada < 8.99){
                    llegada = 9;
                }else if(llegada > 9.60 && llegada < 9.99){
                    llegada = 10;
                }else if(llegada > 10.60 && llegada < 10.99){
                    llegada = 11;
                }else if(llegada > 11.60 && llegada < 11.99){
                    llegada = 12;
                }else if(llegada > 12.60 && llegada < 12.99){
                    llegada = 13;
                }else if(llegada > 13.60 && llegada < 13.99){
                    llegada = 14;
                }else if(llegada > 14.60 && llegada < 14.99){
                    llegada = 15;
                }else if(llegada > 15.60 && llegada < 15.99){
                    llegada = 15;
                }else if(llegada > 16.60 && llegada < 16.99){
                    llegada = 17;
                }

                txtHoraLlegada.setText(txtHoraLlegada.getText() + i + "-. " + llegada + "\n");
            }
            
            /*for(int i = 0; i < personasTotales; i++){
            float tiempoInicial = 7F;
            tiempoInicial = tiempoInsalidaicial + tiempoLlegada[i];
            System.out.println(i + "-. " + tiempoInicial + "\n");
            txtHoraLlegada.setText(txtHoraLlegada.getText() + i + "-. " + tiempoInicial + "\n");
            }*/
        }catch(Exception e){
            System.out.println("Error: " + e);
        }
        
        //Obtener hora salida
        try{
            float contTiempo = 0.08F;
            float contTiempo2 = 0.09F;
            float contTiempo3 = 0.1F;
            float salida = 7F;

            for(int i = 1; i <= personasTotales; i++){
                double y = Math.random();
                float x = (float) y;
                if(x > 0.1 && x < 0.25){
                    salida = salida + contTiempo3;
                }else if(x > 0.25 && x < 0.60){
                    salida = salida + contTiempo2;
                }else if(x > 0.60 && x < 0.99){
                    salida = salida + contTiempo;
                }

                if(salida > 7.60 && salida < 7.99){
                    salida = 8;
                }else if(salida > 8.60 && salida < 8.99){
                    salida = 9;
                }else if(salida > 9.60 && salida < 9.99){
                    salida = 10;
                }else if(salida > 10.60 && salida < 10.99){
                    salida = 11;
                }else if(salida > 11.60 && salida < 11.99){
                    salida = 12;
                }else if(salida > 12.60 && salida < 12.99){
                    salida = 13;
                }else if(salida > 13.60 && salida < 13.99){
                    salida = 14;
                }else if(salida > 14.60 && salida < 14.99){
                    salida = 15;
                }else if(salida > 15.60 && salida < 15.99){
                    salida = 15;
                }else if(salida > 16.60 && salida < 16.99){
                    salida = 17;
                }

                txtSalida.setText(txtSalida.getText() + i + "-. " + salida + "\n");
            }
            /*for(int i = 0; i < personasTotales; i++){
                float salida;
                salida = 7.0F + tiempoLlegada[i];
                txtSalida.setText(txtSalida.getText() + i + "-. " + salida + "\n");
            }*/
        }catch(Exception e){
            System.out.println("Error: " + e);
        }
        
        //Obtener Hora atención
        try{
            float contTiempo = 0.04F;
            float contTiempo2 = 0.05F;
            float contTiempo3 = 0.06F;
            float llegada = 7;

            for(int i = 1; i <= personasTotales; i++){
                double y = Math.random();
                float x = (float) y;
                if(x > 0.1 && x < 0.25){
                    llegada = llegada + contTiempo3;
                }else if(x > 0.25 && x < 0.60){
                    llegada = llegada + contTiempo2;
                }else if(x > 0.60 && x < 0.99){
                    llegada = llegada + contTiempo;
                }

                if(llegada > 7.60 && llegada < 7.99){
                    llegada = 8;
                }else if(llegada > 8.60 && llegada < 8.99){
                    llegada = 9;
                }else if(llegada > 9.60 && llegada < 9.99){
                    llegada = 10;
                }else if(llegada > 10.60 && llegada < 10.99){
                    llegada = 11;
                }else if(llegada > 11.60 && llegada < 11.99){
                    llegada = 12;
                }else if(llegada > 12.60 && llegada < 12.99){
                    llegada = 13;
                }else if(llegada > 13.60 && llegada < 13.99){
                    llegada = 14;
                }else if(llegada > 14.60 && llegada < 14.99){
                    llegada = 15;
                }else if(llegada > 15.60 && llegada < 15.99){
                    llegada = 15;
                }else if(llegada > 16.60 && llegada < 16.99){
                    llegada = 17;
                }

                txtHoraAtencion.setText(txtHoraAtencion.getText() + i + "-. " + llegada + "\n");
            }
            /*txtHoraAtencion.setText(txtHoraAtencion.getText() + "1-. " +7.0 + "\n");
            for(int i = 2; i < personasTotales; i++){
                float horaLlegada;
                horaLlegada = 7.0F + tiempoLlegada[i];
                if(tiempoLlegada[i] > horaSalida){
                    txtHoraAtencion.setText(txtHoraAtencion.getText() + i + "-. " + horaLlegada + "\n");
                }else{
                    txtHoraAtencion.setText(txtHoraAtencion.getText() + i + "-. " + horaSalida + "\n");
                }
            }*/
        }catch(Exception e){
            System.out.println("Error:" + e);
        }
        
        //Obtener el tiempo de cada operacion 
        for(int i = 1; i <= personasTotales; i++){
            double numero = Math.random();
            System.out.print(i + " ");
            if(numero > 0.1 && numero < 0.25){
                cont1 += 1;
                txtTiempoOperacion.setText(txtTiempoOperacion.getText() + i + "-. 00:02:00\n");
            }else if(numero > 0.25 && numero < 0.50){
                cont2 += 1;
                txtTiempoOperacion.setText(txtTiempoOperacion.getText() + i + "-. 00:01:20\n");
            }else if(numero > 0.51 && numero < 0.75){
                cont3 += 1;
                txtTiempoOperacion.setText(txtTiempoOperacion.getText() + i + "-. 00:00:50\n");
            }else{
                cont4 += 1;
                txtTiempoOperacion.setText(txtTiempoOperacion.getText() + i + "-. 00:01:00\n");
            }
        }
        
        //Obtener numeros aleatorios 2
        for(int i = 1; i <= personasTotales; i++){
            double numero = Math.random();
            float numeroFloat;
            numeroFloat = (float) numero;
            txtAleatorio2.setText(txtAleatorio2.getText() + i + "-. " + numeroFloat + "\n");
            System.out.println(i + " " + numeroFloat);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Montecarlo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Montecarlo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Montecarlo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Montecarlo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Montecarlo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRelativa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane txtAleatorio;
    private javax.swing.JTextPane txtAleatorio2;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtConsultaAbsoluta;
    private javax.swing.JTextField txtConsultaRelativa;
    private javax.swing.JTextPane txtHoraAtencion;
    private javax.swing.JTextPane txtHoraLlegada;
    private javax.swing.JTextPane txtOperacion;
    private javax.swing.JTextField txtOtros;
    private javax.swing.JTextField txtOtrosAbsoluta;
    private javax.swing.JTextField txtOtrosRelativa;
    private javax.swing.JTextField txtPersonas;
    private javax.swing.JTextField txtRetiro;
    private javax.swing.JTextField txtRetiroAbsoluta;
    private javax.swing.JTextField txtRetiroRelativa;
    private javax.swing.JTextPane txtSalida;
    private javax.swing.JTextPane txtTiempoLlegada;
    private javax.swing.JTextPane txtTiempoOperacion;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTransferencia;
    private javax.swing.JTextField txtTransferenciaAbsoluta;
    private javax.swing.JTextField txtTransferenciaRelativa;
    private javax.swing.JTextPane txtUsuarios;
    // End of variables declaration//GEN-END:variables
}
